[project]
name = "simpler-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["doughnut", "doughnut_service"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
